<?php
$arr = [
    "Home",
    "About",
    "Story",
    "Package",
    "Members",
    "Blog",
    "Contact",
    "Login",
    "Register",
    "Dashboard",
    "My Profile",
    "2FA Security",
    "Logout",
    "age from",
    "age to",
    "Select Religion",
    "Maritial Status",
    "Select Gender",
    "Male",
    "Female",
    "Search",
    "loader",
    "is typing...",
    "Forget Password",
    "Enter your email address to reset your password",
    "Send Password Reset Link",
    "Don’t have any account? Sign Up",
    "Create account",
    "Reset Password",
    "New Password",
    "Confirm Password",
    "Submit",
    "Don't have an account?",
    "Please confirm your password before continuing.",
    "Forgot Your Password?",
    "Code",
    "Didn't get Code? Click to",
    "Resend code",
    "Email Or Username",
    "Password",
    "Forgot password?",
    "Remember me",
    "sign in",
    "First Name",
    "Last Name",
    "Username",
    "Email Address",
    "Your Phone Number",
    "By signing up you agree to our",
    "T&C.",
    "sign up",
    "Already have an account?",
    "Sign In",
    "Email Verify",
    "Verify Your Email Address",
    "A fresh verification link has been sent to your email address.",
    "Before proceeding, please check your email for a verification link.",
    "If you did not receive the email",
    "click here to request another",
    "403 Forbidden",
    "Forbidden",
    "You don't have permission to access ‘/’ on this server",
    "Back To Home",
    "Opps!",
    "The page you are looking for was not found.",
    "Method Not Allowed",
    "Sorry, your session has expired",
    "Internal Server Error",
    "The server encountered an internal error misconfiguration and was unable to complate your request. Please contact the server administrator.",
    "Email",
    "Phone",
    "faq",
    "contact",
    "Enter email",
    "All Rights Reserved.",
    "Footer image",
    "Previous",
    "Next",
    "You have no notifications",
    "Clear all",
    "blog image",
    "Read more",
    "Counter image",
    "feature image",
    "Free",
    "Express Interests",
    "Gallery Photo Upload",
    "Profile Info View",
    "Show Auto Profile Match",
    "Purchase Package",
    "package image",
    "Close",
    "Purchase Now",
    "No Plan Available.",
    "Price",
    "You can use this package only once. Please purchase new one.",
    "premium member image",
    "premium-member image",
    "story img",
    "show more",
    "story image",
    "No Story Available.",
    "testimonial img",
    "Testimonial image",
    "Payment Failed",
    "Sorry!",
    "We really appreciate you giving us a moment of your time today but unfortunately the payment was unsuccessful due to",
    "it seems some issue in server to server communication. Kindly connect with administrator",
    "Go back to Home",
    "Payment Success",
    "THANK YOU!",
    "Thanks a bunch for filling that out. It means a lot to us, just like you do! We really appreciate you giving us a moment of your time today. Thanks for being wi ▶",
    "Gallery List",
    "Remaining",
    "Gallery Image Upload",
    "Choose image",
    "Upload Image",
    "Image Upload",
    "Gallery Images",
    "gallery img",
    "No Gallery Image Available!",
    "Delete Gallery Image Confirmation",
    "Are Your Sure To Delete This Image?",
    "Yes",
    "Please Upgrade Your Package",
    "Ignored Members",
    "SL.",
    "Name",
    "Age",
    "Religion",
    "Country",
    "Action",
    "ignoreList user img",
    "Delete",
    "No Data Found",
    "Remove From Ignore Confirmation",
    "Are Your Sure To Remove This Member From Your Ignore List?",
    "My Interest List",
    "interestList user img",
    "Are Your Sure To Remove This Member From Your Interest List?",
    "Matched Profile",
    "member post image",
    "Member ID",
    "age",
    "height",
    "religion",
    "caste",
    "location",
    "maritial status",
    "Show Profile",
    "Premium",
    "No Member Available.",
    "Report Member!",
    "Report Reason",
    "You can't shortlist yourself",
    "You can't ignore yourself",
    "Astronomic Information",
    "Sun Sign",
    "Moon Sign",
    "Time Of Birth",
    "City Of Birth",
    "Basic Information",
    "Gender",
    "Date Of Birth",
    "On Behalf",
    "Marital Status",
    "No Of Children",
    "Career Info",
    "SL",
    "Designation",
    "Company",
    "Start Date",
    "End Date",
    "Education Info",
    "Degree",
    "Institution",
    "Family Information",
    "Father",
    "Mother",
    "No. Of Brothers",
    "No. Of Sisters",
    "No. Of Position In Siblings",
    "Hobbies & Interest",
    "Hobbies",
    "Interests",
    "Music",
    "Books",
    "Movies",
    "TV Shows",
    "Sports",
    "Fitness Activities",
    "Cuisines",
    "Dress Styles",
    "Language",
    "Mother Tongue",
    "Known Languages",
    "Lifestyle",
    "Diet",
    "Drink",
    "Smoke",
    "Living With",
    "Partner Expectation",
    "General Requirement",
    "Residence Country",
    "Min Height (In Feet)",
    "Max Weight (In Kg)",
    "Children Acceptancy",
    "Caste",
    "Sub Caste",
    "Education",
    "Profession",
    "Smoking Acceptancy",
    "Drinking Acceptancy",
    "Dieting Acceptancy",
    "Body Type",
    "Personal Value",
    "Manglik",
    "State",
    "City",
    "Family Value",
    "Complexion",
    "Permanent Address",
    "Postal Code",
    "Address",
    "Personal Attitude & Behavior",
    "Affection For",
    "Humor",
    "Political Views",
    "Religious Service",
    "No Gallery Image Available",
    "Physical Attributes",
    "Height (In Feet)",
    "Weight (In Kg)",
    "Eye Color",
    "Hair Color",
    "Blood Group",
    "(A+) Positive",
    "(A-) Negative",
    "(B+) Positive",
    "(B-) Negative",
    "(O+) Positive",
    "(O-) Negative",
    "(AB+) Positive",
    "(AB-) Negative",
    "Body Art",
    "Disability",
    "Present Address",
    "Residency Information",
    "Birth Country",
    "Residency Country",
    "member's image",
    "years",
    "Feet",
    "Interest Expressed",
    "Make Interest",
    "Shortlisted",
    "Shortlist",
    "Ignore",
    "Report",
    "Message",
    "Age from",
    "To",
    "Select Maritial Status",
    "Select Caste",
    "Select Mother Tongue",
    "Select Country",
    "Max Height (In Feet)",
    "Min Height",
    "Profile",
    "Send Message",
    "type here...",
    "Send",
    "No member available for chat",
    "Messenger",
    "Please select a member to chat",
    "Type your message...",
    "feet",
    "view full profile",
    "Can't send empty message",
    "file(s) selected",
    "My Packages",
    "Purchased At",
    "Your Card Information",
    "Enter your card number",
    "Enter the name on your card",
    "Warning",
    "Uh-ho! We are unable to process your Payment by this method.",
    "This method is under construction",
    "Select",
    "bkash",
    "Payment Preview",
    "PLEASE SEND EXACTLY",
    "TO",
    "SCAN TO SEND",
    "Please Pay",
    "To Get",
    "Pay Now",
    "Please follow the instruction below",
    "You have requested to deposit",
    "for successful payment",
    "Change",
    "Remove",
    "Confirm Now",
    "Pay via Monnify",
    "Type Here",
    "All Payment",
    "Pending Payment",
    "Complete Payment",
    "Rejected Payment",
    "Transaction ID",
    "Gateway",
    "Amount",
    "Charge",
    "Status",
    "Time",
    "Detail",
    "Pending",
    "Complete",
    "Cancel",
    "Details",
    "Transactions",
    "Admin Feedback",
    "Payment Information",
    "update",
    "Enter First Name",
    "Enter Last Name",
    "Phone Number",
    "Enter Phone Number",
    "Date of birth",
    "Number Of Childre",
    "Profile Image",
    "user image",
    "Preferred language",
    "Select Language",
    "Add new",
    "N/A",
    "No Career Info Found",
    "Add New Career Info",
    "Your Designation",
    "Company Name",
    "Edit Career Info",
    "Delete Confirmation",
    "Are you sure to delete this?",
    "No Education Info Found",
    "Add New Education Info",
    "Edit Education Info",
    "father",
    "Select One",
    "No",
    "mother",
    "No. of brothers",
    "None",
    "No. of sisters",
    "1st",
    "2nd",
    "3rd",
    "4th",
    "5th",
    "6th",
    "7th",
    "8th",
    "Introduction",
    "Enter Introduction",
    "diet",
    "drink",
    "smoke",
    "Select Residence Country",
    "Does Not Matter",
    "Ex: Fair skin, always burns, sometimes tans",
    "Enter Postal Code",
    "Enter Permanent Address",
    "Select State",
    "Select City",
    "Enter your feeling of liking and caring for someone or something. Ex: Chidren, Parents.",
    "Enter Your Humor",
    "Enter Your Political Views",
    "Enter Your Religious Service",
    "Enter Hair Color",
    "Enter Body Type",
    "Enter Disability",
    "Select Birth Country",
    "Growup Country",
    "Select Growup Country",
    "Immigration Status",
    "Enter Your Immigration Status",
    "Spiritual & Social Background",
    "ethnicity",
    "Ethnicity",
    "personal value",
    "Community Value",
    "community value",
    "Change Password",
    "Current Password",
    "Enter Current Password",
    "Enter New Password",
    "Enter Confirm Password",
    "Update Password",
    "Manage Profile",
    "Congratulations! Your profile is live now",
    "Welldone! Your profile is ready to be approved soon",
    "Please update your profile 100% to get approved",
    "Remove From Shortlist Confirmation",
    "Are Your Sure To Remove This Member From Your Shortlist",
    "Create Story",
    "Enter Name",
    "Place",
    "Enter Place Name",
    "Story Title",
    "Enter Story Title",
    "Description",
    "Privacy",
    "Public",
    "Follower",
    "Only Me",
    "Date",
    "Select a Date",
    "Select Image",
    "Image size should be",
    "px",
    "Add Gallery Images",
    "Create",
    "Preview Image",
    "Remove Image",
    "Edit Story",
    "Existing Gallery Images",
    "Delete Image",
    "Add More New Gallery Images",
    "Story List",
    "No Story Found",
    "Create Ticket",
    "Subject",
    "Enter Subject",
    "Enter Message",
    "Last Reply",
    "Open",
    "Replied",
    "View Details",
    "Customer Reply",
    "Ticket Close Confirmation",
    "Are you sure to close this?",
    "Payment History",
    "Search by Transaction ID",
    "Cancel Payment",
    "2 Step Security",
    "Two Factor Authenticator",
    "Disable Two Factor Authenticator",
    "Enable Two Factor Authenticator",
    "Google Authenticator",
    "Use Google Authenticator to Scan the QR code  or use the code",
    "Google Authenticator is a multifactor app for mobile devices. It generates timed codes used during the 2-step verification process. To use Google Authenticator, ▶",
    "DOWNLOAD APP",
    "Verify Your OTP",
    "Verify",
    "Verify Your OTP to Disable",
    "Add Fund",
    "loading gif",
    "Interest",
    "Profile View",
    "Payment",
    "Plan Name",
    "Transaction Limit:",
    "Payment By",
    "Payable",
    "Conversion Rate",
    "user profile",
    "default image",
    "dashboard",
    "gallery",
    "Manage story",
    "Purchased Packages",
    "shortlist",
    "My Interest",
    "Ignored List",
    "Support Ticket",
    "Change password",
    "About Us",
    "blog img",
    "Posted by",
    "on",
    "Read more...",
    "search",
    "categories",
    "No Post Available",
    "Back",
    "Related Posts",
    "related blog img",
    "contact image",
    "Your name",
    "Frequently Asked Questions",
    "Story Details",
    "photo gallery",
    "Member",
    "Interested",
    "Ignored",
    "Matched",
    "Uploaded",
    "Total",
    "Transaction",
    "Support",
    "Ticket",
    "Sent an image",
    "KB",
    "Image should be less than 3MB!",
];

return $arr;
